name: Build PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra latexmk
      - name: Build PDF
        run: |
          pandoc -s -f gfm Affective-Sovereignty.md -o Affective-Sovereignty.tex
          latexmk -pdf -quiet Affective-Sovereignty.tex
          rm Affective-Sovereignty.tex
      - name: Commit PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Affective-Sovereignty.pdf
          git commit -m "Update generated PDF" || echo "No changes to commit"
          git push
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: |
            Affective-Sovereignty.pdf
            index.html
