name: Build & Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                         # bumped to v4 per upload-pages-artifact’s Dependabot update :contentReference[oaicite:0]{index=0}

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-extra latexmk

      - name: Prepare docs
        run: |
          mkdir docs
          pandoc -s -f gfm Affective-Sovereignty.md -o docs/Affective-Sovereignty.pdf
          latexmk -pdf -quiet docs/Affective-Sovereignty.pdf
          cp index.html docs/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1     # latest v3 as of Feb 7, 2025 :contentReference[oaicite:1]{index=1}
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4                 # latest v4 as of Feb 6, 2025 :contentReference[oaicite:2]{index=2}
