name: Build & Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-extra latexmk

      - name: Prepare docs
        run: |
          mkdir docs
          pandoc -s -f gfm Affective-Sovereignty.md -o docs/Affective-Sovereignty.pdf
          latexmk -pdf -quiet docs/Affective-Sovereignty.pdf
          cp index.html docs/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
